# View the builds at cirrus-ci.com
container:
    image: cirrusci/flutter:stable

env: 
    CODECOV_TOKEN: secret:7KcsYwVDsVDcOTAjfaXjEm2clDNrCWI4eMaPRZYf3VDHAS83dzBF1PCnN4i9ZZ3mrF+Vq6sOtU5s8mPskkg2j+4ZiMIMyyk4VLwuGihsnE0=

task:
  name: Flutter Doctor
  doctor_script: flutter doctor -v
  devices_script: flutter devices

task:
  name: Flutter Unit Tests
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test