name: aspire
description: A new Flutter project.

# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1                  # optional build number separated by a +

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  device_simulator: ^0.9.6
  image_picker: ^0.6.7
  auto_size_text: ^2.1.0
  cloud_firestore: ^0.12.9+5      # firebase database
  cupertino_icons: ^0.1.2         # iOS stye icons
  custom_navigation_bar: ^0.2.6
  device_preview: ^0.4.5
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.6
  flutter_tindercard: ^0.1.8
  google_fonts: ^1.0.0
  intl: ^0.16.1
  url_launcher: ^5.4.10
  effective_dart: ^1.0.0
  cached_network_image: ^2.0.0
  flutter_form_builder: ^3.10.1
  flutter_picker: ^1.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true        # material icon font

  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
