version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter channel stable
      - run: flutter doctor
      - run: flutter test
      - run: flutter -v build apk --debug
