version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: flutter pub get

      - run:
          name: Run Flutter's doctor
          command: flutter doctor

      - run:
          name: Run the application's unit tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk 
      
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
